/** IPC channel names, kept in one place so main and preload can never drift apart. */
export const IPC = {
  settingsGet: 'settings:get',
  settingsUpdate: 'settings:update',
  settingsChanged: 'settings:changed',
  aiStatus: 'ai:status',
  aiRefresh: 'ai:refresh',
  aiConnect: 'ai:connect',
  aiSignIn: 'ai:signIn',
  aiDisconnect: 'ai:disconnect',
  aiOpenKeyPage: 'ai:openKeyPage',
  humanizeRewrite: 'humanize:rewrite',
  humanizeCancel: 'humanize:cancel',
  humanizeChunk: 'humanize:chunk',
  codegenGenerate: 'codegen:generate',
  codegenCancel: 'codegen:cancel',
  codegenChunk: 'codegen:chunk',
  projectPick: 'project:pick',
  projectOpen: 'project:open',
  projectReadFile: 'project:readFile',
  windowsList: 'windows:list',
  windowsOpenFile: 'windows:openFile',
  typingStart: 'typing:start',
  typingPause: 'typing:pause',
  typingResume: 'typing:resume',
  typingStop: 'typing:stop',
  typingSetSpeed: 'typing:setSpeed',
  typingEstimate: 'typing:estimate',
  typingGetStatus: 'typing:getStatus',
  typingStatus: 'typing:status',
  filesSave: 'files:save',
  logHistory: 'log:history',
  logEntry: 'log:entry',
  logClear: 'log:clear',
  hotkey: 'hotkey',
  overlayAction: 'overlay:action'
} as const
